### ISSUE TITLE
Error when compiling link-config from crates.io

### ISSUE THREAD

**Issue by jimfleming** [alexcrichton/link-config#18]
Hello! I'm getting this when compiling link-config from crates.io:

```
   Compiling link-config v0.1.1
~/.cargo/registry/src/github.com-1ecc6299db9ec823/link-config-0.1.1/src/lib.rs:60:7: 60:8 error: macros that expand to items must either be surrounded with braces or followed by a semicolon
~/.cargo/registry/src/github.com-1ecc6299db9ec823/link-config-0.1.1/src/lib.rs:60     ) )
```

```
$ rustc --version
rustc 1.0.0-nightly (f1398d273 2015-01-31 20:21:02 +0000)
```

```
$ cargo -V
cargo 0.0.1-pre-nightly (2b9a3d6 2015-01-30 02:47:30 +0000)
```

This is when loading [`nanomsg`](https://crates.io/crates/nanomsg) so it may be due to something else upstream but figured since the error mentioned link-config I figured I'd start here.

**Comment by alexcrichton** [comment]
Ah yes sorry, I'm not actually maintaining this library on crates.io (it's basically a deprecated library in favor of build scripts regardless).

I think I'm going to yank the previous versions there as well. Thanks for the report though!
